spring.application.name=MovieBookingApplication

# Database Configuration
spring.datasource.url=jdbc:mysql://mysql-db:3306/moviebookingapp
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=8Kx2LpQ7m@$#4sV1zW6yA3bC5dE8rG0H
jwt.expiration=86400000