spring.application.name=MovieBookingApplication

# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.glqgahhxxrvbipywixly
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool (IMPORTANT)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=8Kx2LpQ7m@$#4sV1zW6yA3bC5dE8rG0H
jwt.expiration=86400000
